export default {
  SPRITZ_WIDGET_INITIALISED: "SPRITZ_WIDGET_INITIALISED",
  SPRITZ_WIDGET_OPEN: "SPRITZ_WIDGET_OPEN",
  SPRITZ_WIDGET_CLOSE_REQUEST: "SPRITZ_WIDGET_CLOSE_REQUEST",
  SPRITZ_WIDGET_CLOSE: "SPRITZ_WIDGET_CLOSE",
};
