export default {
  SPRITZ_WIDGET_INITIALISED: "SPRITZ_WIDGET_INITIALISED",
  SPRITZ_WIDGET_OPEN: "SPRITZ_WIDGET_OPEN",
  SPRITZ_WIDGET_CLOSE_REQUEST: "SPRITZ_WIDGET_CLOSE_REQUEST",
  SPRITZ_WIDGET_CLOSE: "SPRITZ_WIDGET_CLOSE",
  SPRITZ_ORDER_CREATED: "SPRITZ_ORDER_CREATED",
  SPRITZ_ORDER_CANCELLED: "SPRITZ_ORDER_CANCELLED",
  SPRITZ_ORDER_FAILED: "SPRITZ_ORDER_FAILED",
  SPRITZ_ORDER_SUCCESSFUL: "SPRITZ_ORDER_SUCCESSFUL",
};
